name: Run Tests and Build Frontend

on:
  push:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the frontend project
        env:
          CI: false
        run: npm run build
